"""
Tribal Wars Mobile Automation Engine - Official Build Templates
Constantes imutáveis em memória contendo os 5 modelos padrão oficiais do sistema.
Proíbe qualquer dependência de ficheiros JSON soltos na raiz ou em disco.
"""

from typing import Dict, List, Any, Tuple

# 1. AI - Build Model (ee02gd68de)
TEMPLATE_AI_BUILD_MODEL: Dict[str, Any] = {
    "id": "ee02gd68de",
    "name": "AI - Build Model",
    "is_default": True,
    "target_levels": {
        "main": 20,
        "barracks": 25,
        "stable": 20,
        "garage": 10,
        "snob": 1,
        "smith": 20,
        "place": 1,
        "market": 20,
        "wood": 30,
        "stone": 30,
        "iron": 30,
        "farm": 30,
        "storage": 30,
        "hide": 1,
        "wall": 20,
    },
    "priority_list": [
        ("wood", 1), ("stone", 1), ("iron", 1), ("wood", 2), ("stone", 2),
        ("main", 2), ("main", 3), ("barracks", 1), ("storage", 2), ("farm", 2),
        ("wood", 3), ("stone", 3), ("iron", 2), ("storage", 3), ("farm", 3),
        ("wood", 4), ("stone", 4), ("main", 4), ("main", 5), ("smith", 1),
        ("barracks", 2), ("barracks", 3), ("storage", 4), ("farm", 4),
        ("wood", 5), ("stone", 5), ("iron", 3), ("iron", 4), ("wall", 1),
        ("storage", 5), ("farm", 5), ("main", 6), ("main", 7), ("main", 8),
        ("barracks", 4), ("barracks", 5), ("smith", 2), ("smith", 3), ("smith", 4),
        ("wood", 6), ("stone", 6), ("wood", 7), ("stone", 7), ("iron", 5),
        ("storage", 6), ("storage", 7), ("farm", 6), ("farm", 7), ("wall", 2),
        ("wall", 3), ("main", 9), ("main", 10), ("stable", 1), ("stable", 2),
        ("stable", 3), ("barracks", 6), ("barracks", 7), ("barracks", 8),
        ("wood", 8), ("stone", 8), ("iron", 6), ("wood", 9), ("stone", 9),
        ("iron", 7), ("iron", 8), ("market", 1), ("market", 2), ("market", 3),
        ("storage", 8), ("storage", 9), ("farm", 8), ("farm", 9), ("wall", 4),
        ("wall", 5), ("main", 11), ("main", 12), ("main", 13), ("smith", 5),
        ("smith", 6), ("smith", 7), ("stable", 4), ("stable", 5), ("barracks", 9),
        ("barracks", 10), ("wood", 10), ("stone", 10), ("iron", 9), ("iron", 10),
        ("storage", 10), ("storage", 11), ("farm", 10), ("farm", 11), ("main", 14),
        ("main", 15), ("main", 16), ("main", 17), ("main", 18), ("main", 19),
        ("main", 20), ("smith", 8), ("smith", 9), ("smith", 10), ("smith", 11),
        ("smith", 12), ("smith", 13), ("smith", 14), ("smith", 15), ("smith", 16),
        ("smith", 17), ("smith", 18), ("smith", 19), ("smith", 20), ("market", 10),
        ("garage", 1), ("garage", 2), ("garage", 3), ("garage", 4), ("garage", 5),
        ("snob", 1), ("wood", 20), ("stone", 20), ("iron", 20), ("storage", 20),
        ("farm", 20), ("barracks", 20), ("barracks", 25), ("stable", 15),
        ("stable", 20), ("wall", 15), ("wall", 20), ("wood", 30), ("stone", 30),
        ("iron", 30), ("storage", 30), ("farm", 30),
    ],
}

# 2. Construção (zbhbufxza0q)
TEMPLATE_CONSTRUCAO: Dict[str, Any] = {
    "id": "zbhbufxza0q",
    "name": "Construcao",
    "is_default": True,
    "target_levels": {
        "main": 20,
        "barracks": 20,
        "stable": 15,
        "garage": 5,
        "smith": 20,
        "place": 1,
        "market": 15,
        "wood": 28,
        "stone": 28,
        "iron": 28,
        "farm": 30,
        "storage": 30,
        "wall": 20,
    },
    "priority_list": [
        ("wood", 1), ("stone", 1), ("iron", 1), ("main", 2), ("main", 3),
        ("wood", 2), ("stone", 2), ("storage", 2), ("farm", 2), ("main", 4),
        ("main", 5), ("barracks", 1), ("barracks", 2), ("wood", 3), ("stone", 3),
        ("iron", 2), ("storage", 3), ("farm", 3), ("smith", 1), ("smith", 2),
        ("wood", 4), ("stone", 4), ("iron", 3), ("barracks", 3), ("wall", 1),
        ("storage", 4), ("farm", 4), ("main", 6), ("main", 7), ("main", 8),
        ("wood", 5), ("stone", 5), ("iron", 4), ("barracks", 4), ("barracks", 5),
        ("smith", 3), ("smith", 4), ("smith", 5), ("stable", 1), ("stable", 2),
        ("wood", 6), ("stone", 6), ("iron", 5), ("storage", 5), ("storage", 6),
        ("farm", 5), ("farm", 6), ("main", 9), ("main", 10), ("barracks", 6),
        ("barracks", 7), ("stable", 3), ("stable", 4), ("wood", 7), ("stone", 7),
        ("iron", 6), ("market", 1), ("market", 2), ("storage", 7), ("storage", 8),
        ("farm", 7), ("farm", 8), ("wall", 2), ("wall", 3), ("wall", 4),
        ("main", 11), ("main", 12), ("main", 13), ("main", 14), ("main", 15),
        ("smith", 6), ("smith", 7), ("smith", 8), ("smith", 9), ("smith", 10),
        ("wood", 8), ("stone", 8), ("iron", 7), ("iron", 8), ("barracks", 8),
        ("barracks", 9), ("barracks", 10), ("stable", 5), ("stable", 6), ("market", 3),
        ("market", 4), ("market", 5), ("storage", 9), ("storage", 10), ("farm", 9),
        ("farm", 10), ("main", 16), ("main", 17), ("main", 18), ("main", 19),
        ("main", 20), ("smith", 11), ("smith", 12), ("smith", 13), ("smith", 14),
        ("smith", 15), ("smith", 16), ("smith", 17), ("smith", 18), ("smith", 19),
        ("smith", 20), ("garage", 1), ("garage", 2), ("garage", 3), ("garage", 4),
        ("garage", 5), ("wood", 9), ("wood", 10), ("wood", 11), ("wood", 12),
        ("wood", 13), ("wood", 14), ("wood", 15), ("stone", 9), ("stone", 10),
        ("stone", 11), ("stone", 12), ("stone", 13), ("stone", 14), ("stone", 15),
        ("iron", 9), ("iron", 10), ("iron", 11), ("iron", 12), ("iron", 13),
        ("iron", 14), ("iron", 15), ("storage", 11), ("storage", 12), ("storage", 13),
        ("storage", 14), ("storage", 15), ("farm", 11), ("farm", 12), ("farm", 13),
        ("farm", 14), ("farm", 15), ("barracks", 11), ("barracks", 12), ("barracks", 13),
        ("barracks", 14), ("barracks", 15), ("stable", 7), ("stable", 8), ("stable", 9),
        ("stable", 10), ("wall", 5), ("wall", 6), ("wall", 7), ("wall", 8),
        ("wall", 9), ("wall", 10), ("storage", 16), ("storage", 17), ("storage", 18),
        ("storage", 19), ("storage", 20), ("farm", 16), ("farm", 17), ("farm", 18),
        ("farm", 19), ("farm", 20), ("barracks", 16), ("barracks", 17), ("barracks", 18),
        ("barracks", 19), ("barracks", 20), ("stable", 11), ("stable", 12), ("stable", 13),
        ("stable", 14), ("stable", 15), ("market", 6), ("market", 7), ("market", 8),
        ("market", 9), ("market", 10), ("market", 11), ("market", 12), ("market", 13),
        ("market", 14), ("market", 15), ("wall", 11), ("wall", 12), ("wall", 13),
        ("wall", 14), ("wall", 15), ("wall", 16), ("wall", 17), ("wall", 18),
        ("wall", 19), ("wall", 20), ("wood", 16), ("wood", 17), ("wood", 18),
        ("wood", 19), ("wood", 20), ("wood", 21), ("wood", 22), ("wood", 23),
        ("wood", 24), ("wood", 25), ("wood", 26), ("wood", 27), ("wood", 28),
        ("stone", 16), ("stone", 17), ("stone", 18), ("stone", 19), ("stone", 20),
        ("stone", 21), ("stone", 22), ("stone", 23), ("stone", 24), ("stone", 25),
        ("stone", 26), ("stone", 27), ("stone", 28), ("iron", 16), ("iron", 17),
        ("iron", 18), ("iron", 19), ("iron", 20), ("iron", 21), ("iron", 22),
        ("iron", 23), ("iron", 24), ("iron", 25), ("iron", 26), ("iron", 27),
        ("iron", 28), ("storage", 21), ("storage", 22), ("storage", 23), ("storage", 24),
        ("storage", 25), ("storage", 26), ("storage", 27), ("storage", 28), ("storage", 29),
        ("storage", 30), ("farm", 21), ("farm", 22), ("farm", 23), ("farm", 24),
        ("farm", 25), ("farm", 26), ("farm", 27), ("farm", 28), ("farm", 29),
        ("farm", 30),
    ],
}

# 3. Upar Barbara (4zyrtbsdxa)
TEMPLATE_UPAR_BARBARA: Dict[str, Any] = {
    "id": "4zyrtbsdxa",
    "name": "Upar Barbara",
    "is_default": True,
    "target_levels": {
        "main": 15,
        "barracks": 10,
        "wood": 30,
        "stone": 30,
        "iron": 30,
        "farm": 30,
        "storage": 30,
        "market": 10,
        "wall": 10,
    },
    "priority_list": [
        ("wood", 1), ("stone", 1), ("iron", 1), ("storage", 2), ("farm", 2),
        ("wood", 2), ("stone", 2), ("iron", 2), ("storage", 3), ("farm", 3),
        ("wood", 3), ("stone", 3), ("iron", 3), ("main", 2), ("main", 3),
        ("wood", 4), ("stone", 4), ("iron", 4), ("storage", 4), ("farm", 4),
        ("wood", 5), ("stone", 5), ("iron", 5), ("main", 4), ("main", 5),
        ("storage", 5), ("farm", 5), ("wood", 6), ("stone", 6), ("iron", 6),
        ("wood", 7), ("stone", 7), ("iron", 7), ("storage", 6), ("storage", 7),
        ("farm", 6), ("farm", 7), ("wood", 8), ("stone", 8), ("iron", 8),
        ("wood", 9), ("stone", 9), ("iron", 9), ("storage", 8), ("storage", 9),
        ("farm", 8), ("farm", 9), ("wood", 10), ("stone", 10), ("iron", 10),
        ("main", 6), ("main", 7), ("main", 8), ("main", 9), ("main", 10),
        ("barracks", 1), ("barracks", 2), ("barracks", 3), ("barracks", 4), ("barracks", 5),
        ("storage", 10), ("farm", 10), ("wood", 15), ("stone", 15), ("iron", 15),
        ("storage", 15), ("farm", 15), ("wood", 20), ("stone", 20), ("iron", 20),
        ("storage", 20), ("farm", 20), ("market", 1), ("market", 5), ("market", 10),
        ("wood", 25), ("stone", 25), ("iron", 25), ("storage", 25), ("farm", 25),
        ("wood", 30), ("stone", 30), ("iron", 30), ("storage", 30), ("farm", 30),
    ],
}

# 4. Sprinter BR131 (rtk1zhvuvtr)
TEMPLATE_SPRINTER_BR131: Dict[str, Any] = {
    "id": "rtk1zhvuvtr",
    "name": "Sprinter BR131",
    "is_default": True,
    "target_levels": {
        "main": 20,
        "barracks": 20,
        "stable": 15,
        "garage": 3,
        "smith": 20,
        "place": 1,
        "market": 10,
        "wood": 20,
        "stone": 20,
        "iron": 20,
        "farm": 28,
        "storage": 26,
        "wall": 15,
    },
    "priority_list": [
        ("wood", 1), ("stone", 1), ("iron", 1), ("wood", 2), ("stone", 2),
        ("main", 2), ("main", 3), ("storage", 2), ("barracks", 1), ("farm", 2),
        ("barracks", 2), ("wood", 3), ("stone", 3), ("iron", 2), ("barracks", 3),
        ("storage", 3), ("farm", 3), ("main", 4), ("main", 5), ("smith", 1),
        ("barracks", 4), ("barracks", 5), ("wood", 4), ("stone", 4), ("iron", 3),
        ("storage", 4), ("farm", 4), ("smith", 2), ("smith", 3), ("smith", 4),
        ("smith", 5), ("main", 6), ("main", 7), ("main", 8), ("main", 9),
        ("main", 10), ("stable", 1), ("stable", 2), ("stable", 3), ("stable", 4),
        ("stable", 5), ("wood", 5), ("stone", 5), ("iron", 4), ("iron", 5),
        ("storage", 5), ("storage", 6), ("storage", 7), ("farm", 5), ("farm", 6),
        ("farm", 7), ("barracks", 6), ("barracks", 7), ("barracks", 8),
        ("barracks", 9), ("barracks", 10), ("wood", 6), ("stone", 6), ("iron", 6),
        ("stable", 6), ("stable", 7), ("stable", 8), ("stable", 9), ("stable", 10),
        ("storage", 8), ("storage", 9), ("storage", 10), ("farm", 8), ("farm", 9),
        ("farm", 10), ("main", 11), ("main", 12), ("main", 13), ("main", 14),
        ("main", 15), ("smith", 6), ("smith", 7), ("smith", 8), ("smith", 9),
        ("smith", 10), ("smith", 11), ("smith", 12), ("smith", 13), ("smith", 14),
        ("smith", 15), ("smith", 16), ("smith", 17), ("smith", 18), ("smith", 19),
        ("smith", 20), ("main", 16), ("main", 17), ("main", 18), ("main", 19),
        ("main", 20), ("barracks", 15), ("barracks", 20), ("stable", 15),
        ("storage", 20), ("storage", 26), ("farm", 20), ("farm", 28),
    ],
}

# 5. Pontos Premium (6goivjbmzbh)
TEMPLATE_PONTOS_PREMIUM: Dict[str, Any] = {
    "id": "6goivjbmzbh",
    "name": "Pontos Premium",
    "is_default": True,
    "target_levels": {
        "main": 20,
        "market": 25,
        "wood": 30,
        "stone": 30,
        "iron": 30,
        "storage": 30,
        "farm": 30,
        "wall": 10,
    },
    "priority_list": [
        ("wood", 1), ("stone", 1), ("iron", 1), ("wood", 2), ("stone", 2),
        ("iron", 2), ("storage", 2), ("farm", 2), ("main", 2), ("main", 3),
        ("wood", 3), ("stone", 3), ("iron", 3), ("storage", 3), ("farm", 3),
        ("main", 4), ("main", 5), ("wood", 4), ("stone", 4), ("iron", 4),
        ("storage", 4), ("farm", 4), ("main", 6), ("main", 7), ("main", 8),
        ("wood", 5), ("stone", 5), ("iron", 5), ("storage", 5), ("farm", 5),
        ("market", 1), ("market", 2), ("market", 3), ("market", 4), ("market", 5),
        ("wood", 6), ("stone", 6), ("iron", 6), ("wood", 7), ("stone", 7),
        ("iron", 7), ("storage", 6), ("storage", 7), ("farm", 6), ("farm", 7),
        ("main", 9), ("main", 10), ("market", 6), ("market", 7), ("market", 8),
        ("market", 9), ("market", 10), ("wood", 8), ("stone", 8), ("iron", 8),
        ("wood", 9), ("stone", 9), ("iron", 9), ("wood", 10), ("stone", 10),
        ("iron", 10), ("storage", 8), ("storage", 9), ("storage", 10),
        ("farm", 8), ("farm", 9), ("farm", 10), ("main", 11), ("main", 12),
        ("main", 13), ("main", 14), ("main", 15), ("market", 11), ("market", 12),
        ("market", 13), ("market", 14), ("market", 15), ("storage", 15),
        ("farm", 15), ("wood", 15), ("stone", 15), ("iron", 15), ("main", 16),
        ("main", 17), ("main", 18), ("main", 19), ("main", 20), ("market", 16),
        ("market", 17), ("market", 18), ("market", 19), ("market", 20),
        ("market", 25), ("wood", 20), ("stone", 20), ("iron", 20), ("storage", 20),
        ("farm", 20), ("wood", 25), ("stone", 25), ("iron", 25), ("storage", 25),
        ("farm", 25), ("wood", 30), ("stone", 30), ("iron", 30), ("storage", 30),
        ("farm", 30),
    ],
}

# Lista Oficial dos 5 Templates Padrão Imutáveis
DEFAULT_BUILD_TEMPLATES: List[Dict[str, Any]] = [
    TEMPLATE_AI_BUILD_MODEL,
    TEMPLATE_CONSTRUCAO,
    TEMPLATE_UPAR_BARBARA,
    TEMPLATE_SPRINTER_BR131,
    TEMPLATE_PONTOS_PREMIUM,
]

DEFAULT_BUILD_TEMPLATE_IDS = frozenset([t["id"] for t in DEFAULT_BUILD_TEMPLATES])
